### ISSUE TITLE
5:30 Friday ferry routing

### ISSUE THREAD

**Issue by rafkuhn** [lemongrabs/get-here#15]
The routing from Atlantic indicates the outbound train required to catch the 5:30 ferry departs at 3:05 vs 3:21 from penn. there is in fact a connection on the 3:23 long beach train to the same Babylon/patchougue train. I almost went to penn but double checked fairyschedule.com and turned around

**Comment by zane** [comment]
@rafkuhn We're just piggybacking off of Google Maps API. We have no control over the decisions it makes as to what connections are possible.

**Comment by rafkuhn** [comment]
Aw. Not ideal, but whatcanwedo

**Comment by zane** [comment]
Yeah. 😦
