### ISSUE TITLE
Update Ferry schedule!

### ISSUE THREAD

**Issue by rafkuhn** [lemongrabs/get-here#17]
Hi guys! can we update for 2017 ferry schedule? they're up on the sayvilleferry.com website for the whole summer.

**Comment by zane** [comment]
Hey @rafkuhn! Will do. I've recently left my job so it might take me a bit to get to it, though.

**Comment by zane** [comment]
Just pushed this up, @rafkuhn! Please help me spot check it when you get a moment!

**Comment by rafkuhn** [comment]
yup took a look and it lewks good! Will keep playing with it!
